require("project")

function love.conf(t)
	t.identity = identity                    -- The name of the save directory (string)
    t.appendidentity = appendidentity            -- Search files in source directory before save directory (boolean)
    t.version = loveversion                  -- The LÖVE version this game was made for (string)
    t.console = console                    -- Attach a console (boolean, Windows only)
    t.accelerometerjoystick = accelerometerjoystick      -- Enable the accelerometer on iOS and Android by exposing it as a Joystick (boolean)
    t.externalstorage = externalstorage           -- True to save files (and read from the save directory) in external storage on Android (boolean) 
    t.gammacorrect = gammacorrect              -- Enable gamma-correct rendering, when supported by the system (boolean)

    t.audio.mic = mic                 -- Request and use microphone capabilities in Android (boolean)
    t.audio.mixwithsystem = mixwithsystem        -- Keep background music playing when opening LOVE (boolean, iOS and Android only)

    t.window.title = tname .. tver .. tdever -- The window title (string)
    t.window.icon = icon                 -- Filepath to an image to use as the window's icon (string)
    t.window.width = width               -- The window width (number)
    t.window.height = height               -- The window height (number)
    t.window.borderless = borderless         -- Remove all border visuals from the window (boolean)
    t.window.resizable = resizeable          -- Let the window be user-resizable (boolean)
    t.window.minwidth = minwidth               -- Minimum window width if the window is resizable (number)
    t.window.minheight = minheight              -- Minimum window height if the window is resizable (number)
    t.window.fullscreen = fullscreen         -- Enable fullscreen (boolean)
    t.window.fullscreentype = fullscreentype -- Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
    t.window.vsync = vsync                  -- Vertical sync mode (number)
    t.window.msaa = msaa                   -- The number of samples to use with multi-sampled antialiasing (number)
    t.window.depth = depth                -- The number of bits per sample in the depth buffer
    t.window.stencil = stencil              -- The number of bits per sample in the stencil buffer
    t.window.display = display                -- Index of the monitor to show the window in (number)
    t.window.highdpi = highdpi            -- Enable high-dpi mode for the window on a Retina display (boolean)
    t.window.usedpiscale = usedpiscale         -- Enable automatic DPI scaling when highdpi is set to true as well (boolean)
    t.window.x = x                    -- The x-coordinate of the window's position in the specified display (number)
    t.window.y = y                    -- The y-coordinate of the window's position in the specified display (number)

    t.modules.audio = true              -- Enable the audio module (boolean)
    t.modules.data = true               -- Enable the data module (boolean)
    t.modules.event = true              -- Enable the event module (boolean)
    t.modules.font = true               -- Enable the font module (boolean)
    t.modules.graphics = true           -- Enable the graphics module (boolean)
    t.modules.image = true              -- Enable the image module (boolean)
    t.modules.joystick = true           -- Enable the joystick module (boolean)
    t.modules.keyboard = true           -- Enable the keyboard module (boolean)
    t.modules.math = true               -- Enable the math module (boolean)
    t.modules.mouse = true              -- Enable the mouse module (boolean)
    t.modules.physics = true            -- Enable the physics module (boolean)
    t.modules.sound = true              -- Enable the sound module (boolean)
    t.modules.system = true             -- Enable the system module (boolean)
    t.modules.thread = true             -- Enable the thread module (boolean)
    t.modules.timer = true              -- Enable the timer module (boolean), Disabling it will result 0 delta time in love.update
    t.modules.touch = true              -- Enable the touch module (boolean)
    t.modules.video = true              -- Enable the video module (boolean)
    t.modules.window = true             -- Enable the window module (boolean)
end
